on:
  push:
    branches:
      - main
      - development
name: "Build and Release Android to Firebase"
jobs:
  build:
    name: Build and Release to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.0"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter analyze
      # No flavors for this demo project
      - run: flutter build apk 
      - name: Push to Github Release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}
      # Deploy on Firebase for demo purposes  
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with: 
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          group: internal_testers
          file: build/app/outputs/apk/release/app-release.apk
      # Notifications on slack     
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


